name: Run Tests & Update Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate artifacts and run tests
        run: |
          pnpm generate
          pnpm test -- --coverage

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Generate HTML coverage report
        run: |
          genhtml lcov.info \
            --output-directory coverage-html \
            --title "CSW Locker Contracts Coverage" \
            --show-details --legend

      - name: Commit coverage report
        if: github.event_name == 'push'
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add lcov.info coverage-html/
          if ! git diff --staged --quiet; then
            git commit -m "Update coverage report [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No coverage changes to commit."
          fi
