name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm generate
      - run: pnpm test -- --coverage

      - name: Generate HTML coverage report
        run: |
          if ! git diff --quiet HEAD -- lcov.info 2>/dev/null || [ ! -d "coverage-html" ]; then
            apt-get update && apt-get install -y lcov
            genhtml lcov.info --output-directory coverage-html --title "CSW Locker Contracts Coverage" --show-details --legend
          fi

      - name: Commit coverage report
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add coverage-html/
          # If coverage is not changed, do not commit.
          git diff --staged --quiet || (git commit -m "Update coverage report [skip ci]" && git push)
